### PR TITLE
Stage back end

### PR DESCRIPTION
**Pull request by Sacha-Marciano**
This is the pull request for the stage-back-end of the HelpEat backend

### CODE REVIEW

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [ ]  There are no lint errors. When running `npx eslint .` they should be absent.
   _There is one linter error: https://prnt.sc/9du4wAD0DhXb_
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  TThe following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET returns` data saved by the user.
  - [x] `POST` creates a data item with the data passed inside the request body.
  - [ ] `DELETE` deletes the saved data item using `_id`.
- [x]  Users can't delete saved data from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and data-related routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation has been implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [ ]  In production mode, the database address is taken from `process.env`.
   _In the current implementation the database address is hardcoded and is not taken from the `.env` file_
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [ ]  Storing the secret key for creating a JWT is implemented correctly:
  - [ ] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
    _Please verify the presence of the `.env` file on the server and check the value of the secret key within it, as the same key appears to be used for both development and production modes._
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [ ]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [ ] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [ ]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [ ]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 78

## Additional comments:
-  Could be improved: It might be better, when deleting recipes or adding them to favorites, to take the `recipeId` from the parameters. This way, users wouldn’t need to have access to the `recipeId` to include it in the `req.body`.
- In the recipe Mongoose schema the `image` field is a String, but checked as URL by the celebrate

**Comment by Sacha-Marciano** [comment]
Hi adzhenalieva !
First of all thanks for your very constructive and deep review. It really helps !

I wanted to point that the DELETE route function checkbox was not check. I am confused since the code contains two routes :
- DELETE /recipes
- DELETE /users/favorite 
- DELETE /users/schedule
At least the first route meets the requirement since it deletes the element with the ._id of a recipe, which was created with POST /recipes.

As of v1.2.0 :
Fix linter errors - now running `npm run lint` will result in no errors.
Moved the .env file from server to backend repo on server - now, in production the JWT secret is took from .env
The helmet module is now used
A rate limiter has been set up.

I may not have understand the database adress issue, so I changed the config of the database adress in the code to be taken from process.env.DATABASE_ADRESS, and added a DATABASE_ADRESS to .env . 
Please don't hesitate to tell me if it was an error :)

Again thanks for your work !

**Comment by adzhenalieva** [comment]
# Summary:
## Backend

### Performance Criteria
- [x]  The repository contains all the necessary infrastructure files:
  - [x] `package.json`;
  - [x] `.editorconfig`;
  - [x] `.eslintrc` is required for extending the configuration of airbnb-base
		- [x] `package.json` contains the `devDependencies` needed for the linter to work correctly
		- [x] An exception for `_id` is added
		- [x] The following rules are forbidden: `eslint-disable`, `eslint-disable-line`, and `eslint-disable-next-line`
  - [x] `.gitignore` should contain at least the `node_modules` folder
- [x]  There are no lint errors. When running `npx eslint .` they should be absent.
- [x]  The scripts section of the package.json file contains the following:
  - [x] An `npm run start` command that starts the server on `localhost:3000`.
  - [x] An `npm run dev` command that starts the server on `localhost:3000` with hot reloading.
- [x]  TThe following routes function as described:
  - [x] A request to `GET /users/me` returns information about the user (email and name).
  - [x] `POST /signup` creates a user with the data passed inside the request body.
  - [x] `POST /signin` returns a JWT when the correct email and password are passed in the request body.
  - [x] `GET returns` data saved by the user.
  - [x] `POST` creates a data item with the data passed inside the request body.
  - [x] `DELETE` deletes the saved data item using `_id`.
- [x]  Users can't delete saved data from other user profiles.
- [x]  All routes are protected with authorization, except for `/signin` and `/signup`.
- [x]  User routes and data-related routes are described in separate files.
- [x]  API errors are handled:
  - [x] Error status codes are used: 400, 401, 403, 404, 409, 500.
  - [x] If something is wrong with the request, the server returns a response with an error message and a corresponding status.
  - [x] The error message matches its type.
  - [x] Asynchronous handlers end with a `catch()` block.
  - [x] The API does not return standard database or Node.js errors.
- [x]  Safe password storage has been implemented:
  - [x] Passwords are stored in a hashed form.
  - [x] The API does not return a password hash to the client.
- [x]  Validation has been implemented correctly:
  - [x] Requests are validated before being passed to the controller. The body and (where applicable) headers and parameters are checked against the corresponding schemas. If a request doesn't match the schema, the processing is not passed to the controller and the client receives a validation error.
  - [x] Data is validated before being added to the database.
- [x]  In production mode, the database address is taken from `process.env`.
- [x]  The server can be accessed via HTTPS using the domain specified in README.md.
- [x]  Storing the secret key for creating a JWT is implemented correctly:
  - [x] In production (i.e., when deployed to the server), the secret key should be stored in a .env file, and this file should not be added to Git.
  - [x] In development (i.e., when run on localhost), the code should run and function correctly, even though there is no .env file present.

### Best Practices
- [x]  All routes are connected to the `index.js` file, which is located in the `routes` folder, and `app.js` contains one main route handled by routes.
- [x]  Asynchronous operations are implemented using promises or async/await.
- [x]  Validation is described in a separate module.
- [x]  Logging is set up:
  - [x] All requests and responses are logged to the `request.log` file.
  - [x] All errors are logged to the `error.log` file.
  - [x] Log files aren't added to the git repository.
- [x]  Errors are handled by a centralized handler.
- [x]  Centralized error handling is described inside a separate module.
- [x]  The application API is located in an /api subdirectory or on an api. subdomain (not just name.zone)
  - [x] Correct:  domain-name.tk/api or api.domain-name.tk
  - [x] Incorrect: domain-name.tk


### Recommendations
- [x]  For API errors, classes have been created to extend the Error constructor.
- [x]  The Helmet module is used to set security-related headers.
- [ ]  Configuration and constants are stored in separate files:
  - [x] The Mongo server address and the private key for the JWT in development mode are stored inside a separate configuration file.
  - [ ] Application constants (response and error messages) are stored inside a separate file with constants.
- [x]  A rate limiter is set up: the number of requests from a single IP address is limited to a particular value in a given amount of time.
- [x]  The rate limiter is configured in a separate file and imported into `app.js`.

## Number of points: 99

## Additional comments:
-  Could be improved: It might be better, when deleting recipes or adding them to favorites, to take the `recipeId` from the parameters. This way, users wouldn’t need to have access to the `recipeId` to include it in the `req.body`.
- In the recipe Mongoose schema the `image` field is a String, but checked as URL by the celebrate

**Comment by adzhenalieva** [comment]
> Hi adzhenalieva ! First of all thanks for your very constructive and deep review. It really helps !
> 
> I wanted to point that the DELETE route function checkbox was not check. I am confused since the code contains two routes :
> 
> * DELETE /recipes
> * DELETE /users/favorite
> * DELETE /users/schedule
>   At least the first route meets the requirement since it deletes the element with the ._id of a recipe, which was created with POST /recipes.
> 
> As of v1.2.0 : Fix linter errors - now running `npm run lint` will result in no errors. Moved the .env file from server to backend repo on server - now, in production the JWT secret is took from .env The helmet module is now used A rate limiter has been set up.
> 
> I may not have understand the database adress issue, so I changed the config of the database adress in the code to be taken from process.env.DATABASE_ADRESS, and added a DATABASE_ADRESS to .env . Please don't hesitate to tell me if it was an error :)
> 
> Again thanks for your work !

Hi, Sacha!

I missed the delete checkbox in the last review—my apologies for the oversight.

The database issue is resolved correctly, as are the other issues. Well done!

**Pull request merged**
